dump cudaOccDeviceProp
pytorch/kineto pull request #209
Opened 2021-05-10 09:22 UTC by gaoteng-git

Dump cudaOccDeviceProp to json trace file, for post-processing occupancy's timeline in tb_plugin.

Example output:
  "metadata": {
      "cudaOccDeviceProps": [{"computeMajor": 7, "computeMinor": 0, "maxThreadsPerBlock": 1024, "maxThreadsPerMultiprocessor": 2048, "regsPerBlock": 65536, "regsPerMultiprocessor": 65536, "warpSize": 32, "sharedMemPerBlock": 49152, "sharedMemPerMultiprocessor": 98304, "numSms": 80, "sharedMemPerBlockOptin": 98304}, {"computeMajor": 7, "computeMinor": 0, "maxThreadsPerBlock": 1024, "maxThreadsPerMultiprocessor": 2048, "regsPerBlock": 65536, "regsPerMultiprocessor": 65536, "warpSize": 32, "sharedMemPerBlock": 49152, "sharedMemPerMultiprocessor": 98304, "numSms": 80, "sharedMemPerBlockOptin": 98304}, {"computeMajor": 7, "computeMinor": 0, "maxThreadsPerBlock": 1024, "maxThreadsPerMultiprocessor": 2048, "regsPerBlock": 65536, "regsPerMultiprocessor": 65536, "warpSize": 32, "sharedMemPerBlock": 49152, "sharedMemPerMultiprocessor": 98304, "numSms": 80, "sharedMemPerBlockOptin": 98304}, {"computeMajor": 7, "computeMinor": 0, "maxThreadsPerBlock": 1024, "maxThreadsPerMultiprocessor": 2048, "regsPerBlock": 65536, "regsPerMultiprocessor": 65536, "warpSize": 32, "sharedMemPerBlock": 49152, "sharedMemPerMultiprocessor": 98304, "numSms": 80, "sharedMemPerBlockOptin": 98304}]
  },

2021-05-10 17:32 UTC, gdankel commented
I think it's better to handle this in handleTraceStart, and I might also dispense with the "metadata" wrapper - seems unnecessary - unless you want to keep it?

2021-05-11 01:03 UTC, gaoteng-git commented
> dispense

Do you mean put the key "cudaOccDeviceProps" to the same level as "schemaVersion", "metadata" and "traceEvents"? Yes, it could work fine, I'll try it.

2021-05-11 01:04 UTC, gaoteng-git commented
> I think it's better to handle this in handleTraceStart, and I might also dispense with the "metadata" wrapper - seems unnecessary - unless you want to keep it?

Do you mean put the key "cudaOccDeviceProps" to the same level as "schemaVersion", "metadata" and "traceEvents"? Yes, it could work fine, I'll try it.

2021-05-11 02:02 UTC, guotuofeng requested changes

2021-05-11 02:02 UTC, guotuofeng commented on libkineto/src/output_json.cpp
> +  const std::vector<cudaOccDeviceProp>& occProps = KINETO_NAMESPACE::occDeviceProps();
make sure the occDeviceProps call in kernelOccupancy could leverage the metadata as well to fix make the O(n) call to be O(1)?

2021-05-11 02:40 UTC, guotuofeng commented on libkineto/src/output_json.cpp
> +    for (size_t i = 0; i < occProps.size(); i += 1) {
i++ or ++i?

2021-05-11 02:40 UTC, guotuofeng commented on libkineto/src/output_json.cpp
> +      oss << "\"sharedMemPerMultiprocessor\": " << occProp.sharedMemPerMultiprocessor << ", ";
need we consolidate with distributed training metadata like "id", "name" and "total_memory"?

2021-05-11 04:37 UTC, gdankel commented
@gaoteng-git Yes - I did it for you earlier today to save time but could not export it to github until recently due to an internal issue. Here's the PR: https://github.com/pytorch/kineto/pull/211

Note that I had to create a new PR since I cannot update your PR here on GitHub. Take a look and see if it's OK.

2021-05-12 09:43 UTC, closed without merging