Add Logging for Empty Traces
pytorch/kineto pull request #968
Opened 2024-07-26 21:11 UTC by sraikund16

Summary: Recently, we have had users seen empty traces when the system is idle leading to confusion as to whether it was caused by a bug in kineto formatting or not. This diff adds further logging to ensure that the user is aware that kineto finds no valid trace events and is expecting an empty trace.

Differential Revision: D60311331

2024-07-30 17:12 UTC, aaronenyeshi requested changes
Should we also add the functions into roctracer's handleactivity functions?

2024-07-30 17:14 UTC, sraikund16 commented
> Should we also add the functions into roctracer's handleactivity functions?

@aaronenyeshi Sure, can we do that as a followup diff instead?

2024-07-31 15:52 UTC, aaronenyeshi commented
> > Should we also add the functions into roctracer's handleactivity functions?
> 
> @aaronenyeshi Sure, can we do that as a followup diff instead?

yes that sounds good

2024-07-31 15:54 UTC, aaronenyeshi approved these changes
LGTM, small nit

2024-07-31 15:54 UTC, aaronenyeshi commented on libkineto/src/CuptiActivityProfiler.cpp
> +    LOG(WARNING) << "No Valid Trace Events found. Outputting empty trace.";
Could we clarify this means no CPU and GPU events?

2024-08-01 17:14 UTC, sraikund16 commented
> > > Should we also add the functions into roctracer's handleactivity functions?
> > 
> > 
> > @aaronenyeshi Sure, can we do that as a followup diff instead?
> 
> yes that sounds good

Looking at it now, I think this already covers the roctracer impl. handleGpuActivity with ItraceActivity as an arg is shared between CUPTI and Rocm, and the Rocm handleRuntimeActivity is also covered in this diff. We will see for sure when the next diff tests on all architectures though

2024-08-01 19:43 UTC, closed without merging